#+HTML_HEAD: <style type="text/css">body { font-family: Fira Sans, Helvetica, Arial, sans-serif; }</style>

* My Talks

- [[file:2016-02-munich-rubyshift/][2016-02-munich-rubyshift/]]
- [[file:2016-01-munich-rubyshift/][2016-01-munich-rubyshift/]]
- [[file:2015-12-munich-rubyshift/][2015-12-munich-rubyshift/]]
- [[file:2015-11-munich-rubyshift/][2015-11-munich-rubyshift/]]
- [[file:2015-10-munich-rubyshift/][2015-10-munich-rubyshift/]]
- [[file:2015-05-munich-rubyshift/][2015-05-munich-rubyshift/]]
- [[file:2015-03-munich-rubyshift/][2015-03-munich-rubyshift/]]
- [[file:2014-leipzig-js/][2014-leipzig-js/]]
- [[file:2014-cologne-js/][2014-cologne-js/]]
- [[file:2012-lightning-io/][2012-lightning-io/]]
- [[file:2012-cologne.rb/][2012-cologne.rb/]]
- [[file:2012-cologne-rb-vagrant/][2012-cologne-rb-vagrant/]]
- [[file:2012-cologne-rb-faceblock/][2012-cologne-rb-faceblock/]]
- [[file:2011-pyconde/][2011-pyconde/]]

This is a (non-comprehensive) list of talks I gave at various user
groups & conferences. If you have any questions, feel free to reach
out for me via a GitHub issue in this repo.

** Found license issues & copyright violations?
I tried my best to keep the original licenses and give credit to
original authors. If you miss photos from a Talk I gave, that probably
means that I couldn't find the author of the image or give proper
attribution.

If you find photos / images / text content in this repository that
violates intellectual property, please notify me at ~github dot com at
bascht dot com~ and I will take it down.

** License
Unless noted otherwise, all content in this repository is free for you
to use under the terms of the [[http://creativecommons.org/licenses/by-sa/4.0/][Attribution-ShareAlike 4.0 International
(CC BY-SA 4.0)]] license.

Generated: 2016-02-10 18:49:22 +0100
